#pragma once
#define MIN_PIXEL_FOR_COLISION 10

#define PREPARE_DURATION_MS 3000
#define TURN_DURATION_MS 10000

// Player
#define BUFFERSIZE 8
#define PLAYER_IMAGE_SIZE {40, 40}
#define PLAYER_HITBOX_SIZE {30,30}

// Caneta estourada
#define PLAYERPEN_NAME "Caneta"
#define PLAYERPEN_SPLASH_INTERVAL_MS 2500
#define PLAYERPEN_SPLASH_GROWTH_MS 2000
#define PLAYERPEN_SPLASH_START_SIZE {10, 10}
#define PLAYERPEN_SPLASH_IMAGE_SIZE {40, 40}
#define PLAYERPEN_SPLASH_HITBOX_SIZE {30, 30}
#define PLAYERPEN_SPLASH_IMAGE "assets/images/orange.png"

// Mochila Bomba
#define PLAYERBAG_NAME "Mochila"
#define PLAYERBAG_DROP_INTERVAL_MS 1500
#define PLAYERBAG_DROP_GROWTH_MS 100
#define PLAYERBAG_DROP_START_SIZE {10, 10}
#define PLAYERBAG_DROP_IMAGE_SIZE {35, 35}
#define PLAYERBAG_DROP_HITBOX_SIZE {25, 25}
#define PLAYERBAG_DROP_IMAGE "assets/images/orange.png"
#define PLAYERBAG_DROP_VELOCITY 50
