#pragma once
#define MIN_PIXEL_FOR_COLISION 1

#define DRAWHIBOXES // Remover para parar de desenhar hitboxes

#define PREPARE_DURATION_MS 3000
#define TURN_DURATION_MS 10000

// Player
#define BUFFERSIZE 8
#define PLAYER_IMAGE_SIZE {40, 40}
#define PLAYER_HITBOX_SIZE {30,30}

// Caneta estourada
#define PLAYERPEN_NAME "Caneta"
#define PLAYERPEN_SPLASH_INTERVAL_MS 2500
#define PLAYERPEN_SPLASH_GROWTH_MS 2000
#define PLAYERPEN_SPLASH_START_SIZE {10, 10}
#define PLAYERPEN_SPLASH_IMAGE_SIZE {40, 40}
#define PLAYERPEN_SPLASH_HITBOX_SIZE {30, 30}
#define PLAYERPEN_SPLASH_IMAGE "assets/images/inksplash.png"

// Mochila Bomba
#define PLAYERBAG_NAME "Mochila"
#define PLAYERBAG_DROP_INTERVAL_MS 1500
#define PLAYERBAG_DROP_GROWTH_MS 100
#define PLAYERBAG_DROP_START_SIZE {10, 10}
#define PLAYERBAG_DROP_IMAGE_SIZE {35, 35}
#define PLAYERBAG_DROP_HITBOX_SIZE {25, 25}
#define PLAYERBAG_DROP_IMAGE "assets/images/caderno.png"
#define PLAYERBAG_DROP_VELOCITY 50

// Marmita Cobiçada
#define PLAYERDOG_NAME "Marmita"
#define PLAYERDOG_GROWTH_MS 1000
#define PLAYERDOG_START_SIZE {10, 10}
#define PLAYERDOG_IMAGE_SIZE {35, 35}
#define PLAYERDOG_HITBOX_SIZE {25, 25}
#define PLAYERDOG_IMAGE "assets/images/dog.png"
#define PLAYERDOG_VELOCITY 25

// Liga elastica
#define PLAYERRUBBER_NAME "Liga"
#define PLAYERRUBBER_GROWTH_MS 1000
#define PLAYERRUBBER_START_SIZE {10, 10}
#define PLAYERRUBBER_IMAGE_SIZE {30, 30}
#define PLAYERRUBBER_HITBOX_SIZE {15, 15}
#define PLAYERRUBBER_IMAGE "assets/items/Liga/imagem.png"
#define PLAYERRUBBER_VELOCITY 75
#define PLAYERRUBBER_SPAWN_TIME 4000

// Ar não condicionado
#define PLAYERAIR_NAME "Ar-nao-condicionado"
#define PLAYERAIR_DROP_GROWTH_MS 1000
#define PLAYERAIR_DEVICE_SIZE {50,50}
#define PLAYERAIR_DROP_START_SIZE {10, 10}
#define PLAYERAIR_DROP_IMAGE_SIZE {30, 30}
#define PLAYERAIR_DROP_HITBOX_SIZE {15, 15}
#define PLAYERAIR_DEVICE_IMAGE "assets/images/arcondicionado.png"
#define PLAYERAIR_DROP_IMAGE "assets/images/gotas.png"
#define PLAYERAIR_DROP_VELOCITY 50
#define PLAYERAIR_DROP_INTERVAL_MS 4000

// Força que o jogo só dê esse item
#define ONLY_ITEM_NAME PLAYERDOG_NAME